version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tez_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tezler
      MYSQL_USER: tez_user
      MYSQL_PASSWORD: tez_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
